# -*- coding: utf-8 -*-
"""
识图题题库 - 完整版（已合并多标记图为单题）
"""

SHITU_QUESTIONS = [
    {
        "id": "shitu_samerica_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为南美洲地形图，图中标注了主要海洋、地形区和河流。请按顺序填写各标号名称：\n①____ ②____ ③____ ④____ ⑤____ ⑥____\n⑦____ ⑧____ ⑨____ ⑩____ ⑪____ ⑫____",
        "image": "1.png",
        "answer": ["太平洋", "大西洋", "亚马孙平原", "巴西高原", "安第斯山脉", "圭亚那高原", "巴拉那高原", "拉普拉塔平原", "火地岛", "南极半岛", "亚马孙河", "巴拉那河"],
        "explanation": "南美洲地形特征：①太平洋（西侧）、②大西洋（东侧）；③亚马孙平原（世界最大平原）、④巴西高原（世界最大高原）、⑤安第斯山脉（世界最长山脉）；⑥圭亚那高原、⑦巴拉那高原、⑧拉普拉塔平原；⑨火地岛（南端）、⑩南极半岛；⑪亚马孙河（世界流量最大河流）、⑫巴拉那河。",
    },
    {
        "id": "shitu_asia_climate_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为亚洲气候类型分布图，图中字母A-H表示不同气候区域。请按顺序填写各字母代表的气候类型：\nA____ B____ C____ D____\nE____ F____ G____ H____",
        "image": "10.png",
        "answer": ["温带季风气候", "亚热带季风气候", "热带季风气候", "高原山地气候", "温带大陆性气候", "热带雨林气候", "热带沙漠气候", "地中海气候"],
        "explanation": "亚洲气候复杂多样：A温带季风气候（中国东北、日本北部）、B亚热带季风气候（中国东南、日本南部）、C热带季风气候（南亚、东南亚）、D高原山地气候（青藏高原）；E温带大陆性气候（中亚、西伯利亚）、F热带雨林气候（马来群岛）、G热带沙漠气候（西亚阿拉伯半岛）、H地中海气候（西亚地中海沿岸）。",
    },
    {
        "id": "shitu_plate_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为全球六大板块分布图，图中数字①-⑥表示六大板块。请按顺序填写各数字代表的板块名称：\n①____ ②____ ③____ ④____ ⑤____ ⑥____",
        "image": "13.png",
        "answer": ["亚欧板块", "非洲板块", "印度洋板块", "太平洋板块", "美洲板块", "南极洲板块"],
        "explanation": "全球岩石圈分为六大板块：①亚欧板块（最大板块）、②非洲板块、③印度洋板块（含澳大利亚）、④太平洋板块（几乎全为海洋）、⑤美洲板块、⑥南极洲板块。板块交界处地壳活跃，多火山地震。",
    },
    {
        "id": "shitu_asia_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为亚洲政区与地形图，图中字母A-N标注了主要地理事物。请按顺序填写各字母代表的地理事物：\nA____ B____ C____ D____\nE____ F____ G____ H____\nI____ J____ K____ L____\nM____ N____",
        "image": "15.png",
        "answer": ["印度半岛", "孟加拉国", "青藏高原", "西伯利亚", "土耳其", "东西伯利亚", "阿拉伯半岛", "地中海", "马来群岛", "中国东部", "巴基斯坦", "印度半岛南部", "中亚", "伊朗"],
        "explanation": "亚洲主要地理事物：A印度半岛（南亚最大半岛）、B孟加拉国、C青藏高原（世界屋脊）、D西伯利亚（北亚）；E土耳其（地跨亚欧）、F东西伯利亚、G阿拉伯半岛（世界最大半岛）、H地中海；I马来群岛（世界最大群岛）、J中国东部、K巴基斯坦、L印度半岛南部；M中亚、N伊朗。",
    },
    {
        "id": "shitu_sam_temp_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为南美洲温度带分布图，图中字母A-F标注了温度带和主要地理事物。请按顺序填写：\nA____ B____ C____ D____ E____ F____",
        "image": "16.png",
        "answer": ["热带", "北温带", "南温带", "南寒带", "巴西高原", "圣保罗"],
        "explanation": "南美洲温度带分布：A热带（赤道至南回归线之间，面积最大）、B北温带（北回归线以北，面积很小）、C南温带（南回归线至南极圈）、D南寒带（南极圈以南）；E巴西高原（世界最大高原）、F圣保罗（巴西最大城市）。",
    },
    {
        "id": "shitu_aus_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为澳大利亚气候类型分布图。图中字母A-F表示不同气候区域，数字①-⑥表示东南沿海主要城市。请按顺序填写：\n①____ ②____ ③____ ④____ ⑤____ ⑥____",
        "image": "17.png",
        "answer": ["布里斯班", "悉尼", "墨尔本", "阿德莱德", "堪培拉", "霍巴特"],
        "explanation": "澳大利亚东南沿海是人口和城市集中分布区：①布里斯班（昆士兰州首府，东北沿海）→②悉尼（新南威尔士州首府，最大城市）→③墨尔本（维多利亚州首府，第二大城市）→④阿德莱德（南澳大利亚州首府）→⑤堪培拉（首都，位于悉尼西南内陆）→⑥霍巴特（塔斯马尼亚州首府）。字母A-F为气候区：A热带雨林、B亚热带湿润、C热带草原、D热带沙漠、E地中海、F温带海洋性。",
    },
    {
        "id": "shitu_na_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为北美洲地形与海陆分布图，图中字母A-F表示海洋海湾，数字①-⑨表示主要地理事物。请按顺序填写：\nA____ B____ C____ D____ E____ F____\n①____ ②____ ③____ ④____ ⑤____\n⑥____ ⑦____ ⑧____ ⑨____",
        "image": "2.png",
        "answer": ["北冰洋", "太平洋", "大西洋", "墨西哥湾", "加勒比海", "白令海峡", "密西西比河", "西印度群岛", "格陵兰岛", "拉布拉多高原", "阿巴拉契亚山脉", "大平原", "落基山脉", "密西西比河", "圣劳伦斯河"],
        "explanation": "北美洲地理特征：海洋-A北冰洋（北）、B太平洋（西）、C大西洋（东）、D墨西哥湾（南）、E加勒比海、F白令海峡（西北与亚洲分界）；①密西西比河、②西印度群岛、③格陵兰岛（世界最大岛）、④拉布拉多高原、⑤阿巴拉契亚山脉（东部）、⑥大平原（中部）、⑦落基山脉（西部）、⑧密西西比河、⑨圣劳伦斯河。",
    },
    {
        "id": "shitu_africa_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为非洲地形图，图中数字①-⑪表示大洲大洋与地理事物，字母A-G表示地形区。请按顺序填写：\n①____ ②____ ③____ ④____ ⑤____ ⑥____\n⑦____ ⑧____ ⑨____ ⑩____ ⑪____\nA____ B____ C____ D____\nE____ F____ G____",
        "image": "5.png",
        "answer": ["欧洲", "亚洲", "大西洋", "印度洋", "几内亚湾", "地中海", "尼罗河", "刚果河", "维多利亚湖", "马达加斯加岛", "索马里半岛", "东非大裂谷", "刚果盆地", "埃塞俄比亚高原", "南非高原", "东非高原", "乞力马扎罗山", "撒哈拉沙漠"],
        "explanation": "非洲地理特征：①欧洲（北隔地中海）、②亚洲（东北隔红海）、③大西洋（西）、④印度洋（东）、⑤几内亚湾（西非海岸）、⑥地中海；⑦尼罗河（世界最长河）、⑧刚果河、⑨维多利亚湖（非洲最大湖）、⑩马达加斯加岛（东岸最大岛）、⑪索马里半岛；地形区-A东非大裂谷、B刚果盆地、C埃塞俄比亚高原、D南非高原、E东非高原、F乞力马扎罗山（非洲最高峰）、G撒哈拉沙漠（世界最大沙漠）。",
    },
    {
        "id": "shitu_china_river_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为亚洲主要河流分布图，图中数字①-⑩标注了主要河流。请按顺序填写各数字代表的河流名称：\n①____ ②____ ③____ ④____ ⑤____\n⑥____ ⑦____ ⑧____ ⑨____ ⑩____",
        "image": "9.png",
        "answer": ["勒拿河", "叶尼塞河", "额尔齐斯河", "黄河", "长江", "黑龙江", "珠江", "雅鲁藏布江", "塔里木河", "澜沧江"],
        "explanation": "亚洲主要河流：①勒拿河、②叶尼塞河、③额尔齐斯河（北冰洋水系）；④黄河（中国第二长河）、⑤长江（中国第一长河，世界第三）、⑥黑龙江；⑦珠江（华南最大水系）、⑧雅鲁藏布江（西藏，下游为布拉马普特拉河）、⑨塔里木河（中国最长内流河）、⑩澜沧江（下游为湄公河）。",
    },
    {
        "id": "shitu_microscope_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为显微镜结构图，图中数字1-11标注了显微镜的主要部件。请按顺序填写各数字代表的结构名称：\n①____ ②____ ③____ ④____ ⑤____\n⑥____ ⑦____ ⑧____ ⑨____ ⑩____ ⑪____",
        "image": "image1.png",
        "answer": ["目镜", "转换器", "物镜", "压片夹", "载物台", "通光孔", "粗准焦螺旋", "细准焦螺旋", "移动手轮(或玻片移动器)", "光源(或底光源/反光镜)", "电源开关及亮度调节旋钮"],
        "explanation": "显微镜主要结构：①目镜（靠近眼睛，放大物像）、②转换器（转换物镜）、③物镜（靠近标本，放大物像）；④压片夹、⑤载物台（放置标本）、⑥通光孔；⑦粗准焦螺旋（大幅度升降镜筒）、⑧细准焦螺旋（精细调焦）；⑨移动手轮（移动标本）、⑩光源/反光镜（提供照明）、⑪电源开关及亮度调节旋钮。",
    },
    {
        "id": "shitu_class_03",
        "chapter_id": "bio_8_6_1",
        "image": "image100.png",
        "question": "图中哪种动物的种类最多?",
        "type": "select",
        "options": ["哺乳动物", "鸟类", "节肢动物", "鱼类"],
        "answer": 2,
        "explanation": "节肢动物是动物界中种类最多、数量最大、分布最广的类群。",
    },
    {
        "id": "shitu_class_04",
        "chapter_id": "bio_8_6_1",
        "image": "image100.png",
        "question": "下列哪类植物有种子?",
        "type": "select",
        "options": ["苔藓植物", "蕨类植物", "被子植物", "藻类植物"],
        "answer": 2,
        "explanation": "被子植物和裸子植物都有种子,称为种子植物。",
    },
    {
        "id": "shitu_genetic_01",
        "chapter_id": "bio_8_5_3",
        "image": "image101.png",
        "question": "父亲体细胞中染色体组成是?",
        "type": "select",
        "options": ["22对+XX", "22对+XY", "23对+XX", "23对+XY"],
        "answer": 1,
        "explanation": "父亲体细胞有22对常染色体+XY性染色体。",
    },
    {
        "id": "shitu_genetic_02",
        "chapter_id": "bio_8_5_3",
        "image": "image101.png",
        "question": "精子中染色体组成是?",
        "type": "select",
        "options": ["X或Y", "XX", "XY", "YY"],
        "answer": 0,
        "explanation": "精子含X或Y染色体,卵细胞只含X染色体。",
    },
    {
        "id": "shitu_genetic_03",
        "chapter_id": "bio_8_5_3",
        "image": "image101.png",
        "question": "生男生女由谁决定?",
        "type": "select",
        "options": ["母亲", "父亲", "双方共同决定", "环境"],
        "answer": 1,
        "explanation": "生男生女取决于父亲提供的精子含X还是Y染色体。",
    },
    {
        "id": "shitu_genetic_04",
        "chapter_id": "bio_8_5_3",
        "image": "image102.png",
        "question": "卵细胞中染色体组成是?",
        "type": "select",
        "options": ["X", "Y", "X或Y", "XY"],
        "answer": 0,
        "explanation": "卵细胞只携带X染色体,因为女性体细胞中是XX。",
    },
    {
        "id": "shitu_seed_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为菜豆种子结构图，图中数字1-6标注了种子的各部分结构。请按顺序填写各数字代表的结构名称：\n①____ ②____ ③____ ④____ ⑤____ ⑥____",
        "image": "image12.png",
        "answer": ["胚轴", "胚芽", "胚根", "子叶(储存营养物质)", "胚(由胚轴、胚芽、胚根和子叶组成)", "种皮(保护作用)"],
        "explanation": "菜豆种子结构：①胚轴（连接胚芽和胚根）、②胚芽（发育成茎和叶）、③胚根（发育成根）、④子叶（储存营养物质，菜豆有两片子叶）；⑤胚（由胚轴、胚芽、胚根和子叶组成，是种子的主要部分）、⑥种皮（保护作用）。",
    },
    {
        "id": "shitu_paramecium_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为草履虫结构图，图中数字1-10标注了草履虫的主要结构。请按顺序填写各数字代表的结构名称：\n①____ ②____ ③____ ④____ ⑤____\n⑥____ ⑦____ ⑧____ ⑨____ ⑩____",
        "image": "image14.png",
        "answer": ["胞肛", "食物泡", "口沟", "纤毛(运动)", "细胞质", "大核(或细胞核)", "小核", "表膜(或细胞膜)", "伸缩泡(收集排出多余水分)", "收集管"],
        "explanation": "草履虫结构：①胞肛（排出食物残渣）、②食物泡（消化食物）、③口沟（摄取食物）、④纤毛（运动器官，摆动使草履虫旋转前进）、⑤细胞质；⑥大核（营养代谢）、⑦小核（生殖遗传）、⑧表膜/细胞膜（呼吸和排泄）、⑨伸缩泡（收集排出多余水分）、⑩收集管（收集水分）。",
    },
    {
        "id": "shitu_grasshopper_01",
        "chapter_id": "bio_7_2_3",
        "image": "image15.png",
        "question": "蝗虫的身体分为几个部分?",
        "type": "select",
        "options": ["两部分", "三部分", "四部分", "五部分"],
        "answer": 1,
        "explanation": "蝗虫身体分为头部、胸部、腹部三部分。",
    },
    {
        "id": "shitu_grasshopper_05",
        "chapter_id": "bio_7_2_3",
        "image": "image15.png",
        "question": "蝗虫的呼吸器官是?",
        "type": "select",
        "options": ["肺", "气管", "鳃", "皮肤"],
        "answer": 1,
        "explanation": "蝗虫通过气门与气管相连,进行气体交换。",
    },
    {
        "id": "shitu_earthworm_04",
        "chapter_id": "bio_7_2_3",
        "image": "image16.png",
        "question": "蚯蚓依靠什么结构运动?",
        "type": "select",
        "options": ["1体节", "2刚毛", "3环带", "翅膀"],
        "answer": 1,
        "explanation": "蚯蚓依靠刚毛和肌肉的配合进行运动。",
    },
    {
        "id": "shitu_hydra_04",
        "chapter_id": "bio_7_2_3",
        "image": "image17.png",
        "question": "水螅属于哪类动物?",
        "type": "select",
        "options": ["扁形动物", "线形动物", "刺胞动物", "环节动物"],
        "answer": 2,
        "explanation": "水螅属于刺胞动物,身体呈辐射对称。",
    },
    {
        "id": "shitu_planarian_01",
        "chapter_id": "bio_7_2_3",
        "image": "image18.png",
        "question": "图中①眼点的作用是?",
        "type": "select",
        "options": ["嗅觉", "视觉", "听觉", "触觉"],
        "answer": 1,
        "explanation": "涡虫有眼点,能感知光线强弱。",
    },
    {
        "id": "shitu_planarian_02",
        "chapter_id": "bio_7_2_3",
        "image": "image18.png",
        "question": "图中③咽的作用是?",
        "type": "select",
        "options": ["呼吸", "消化", "运动", "生殖"],
        "answer": 1,
        "explanation": "涡虫用咽摄取食物,食物在肠内消化。",
    },
    {
        "id": "shitu_frog_04",
        "chapter_id": "bio_7_2_3",
        "image": "image20.png",
        "question": "青蛙的呼吸器官是?",
        "type": "select",
        "options": ["肺", "鳃", "气管", "皮肤"],
        "answer": 0,
        "explanation": "青蛙主要用肺呼吸,皮肤辅助呼吸。",
    },
    {
        "id": "shitu_fish_03",
        "chapter_id": "bio_7_2_3",
        "image": "image21.png",
        "question": "鱼用什么呼吸?",
        "type": "select",
        "options": ["肺", "鳃", "气管", "皮肤"],
        "answer": 1,
        "explanation": "鱼用鳃呼吸,水流经鳃丝时进行气体交换。",
    },
    {
        "id": "shitu_reptile_01",
        "chapter_id": "bio_7_2_3",
        "image": "image22.png",
        "question": "爬行动物体表覆盖什么?",
        "type": "select",
        "options": ["羽毛", "鳞片", "毛皮", "裸露皮肤"],
        "answer": 1,
        "explanation": "爬行动物体表覆盖鳞片,可减少水分蒸发。",
    },
    {
        "id": "shitu_reptile_02",
        "chapter_id": "bio_7_2_3",
        "image": "image22.png",
        "question": "爬行动物颈部的作用是?",
        "type": "select",
        "options": ["美观", "增加灵活性", "支撑身体", "保护内脏"],
        "answer": 1,
        "explanation": "颈部使头部能灵活转动,便于捕食和避敌。",
    },
    {
        "id": "shitu_rabbit_01",
        "chapter_id": "bio_7_2_3",
        "image": "image23.png",
        "question": "图中膈肌是什么动物特有的结构?",
        "type": "select",
        "options": ["鸟类", "哺乳动物", "爬行动物", "两栖动物"],
        "answer": 1,
        "explanation": "膈肌是哺乳动物特有的结构,将体腔分为胸腔和腹腔。",
    },
    {
        "id": "shitu_rabbit_02",
        "chapter_id": "bio_7_2_3",
        "image": "image23.png",
        "question": "家兔盲肠发达的原因是?",
        "type": "select",
        "options": ["食肉", "食草", "杂食", "滤食"],
        "answer": 1,
        "explanation": "家兔是食草动物,盲肠发达有助于消化植物纤维。",
    },
    {
        "id": "shitu_bird_01",
        "chapter_id": "bio_7_2_3",
        "image": "image25.png",
        "question": "鸟类骨骼的特点是?",
        "type": "select",
        "options": ["全部中空", "部分中空", "没有骨髓", "都很重"],
        "answer": 1,
        "explanation": "鸟类部分骨骼中空,可减轻体重,利于飞行。",
    },
    {
        "id": "shitu_bird_02",
        "chapter_id": "bio_7_2_3",
        "image": "image26.png",
        "question": "鸟类呼吸系统的特点是?",
        "type": "select",
        "options": ["只用肺呼吸", "有气囊辅助呼吸", "用皮肤呼吸", "用鳃呼吸"],
        "answer": 1,
        "explanation": "鸟类有气囊,气囊辅助肺进行双重呼吸。",
    },
    {
        "id": "shitu_mushroom_02",
        "chapter_id": "bio_8_6_2",
        "image": "image30.png",
        "question": "蘑菇靠什么繁殖后代?",
        "type": "select",
        "options": ["种子", "孢子", "芽体", "卵细胞"],
        "answer": 1,
        "explanation": "蘑菇属于真菌,靠孢子繁殖后代。",
    },
    {
        "id": "shitu_virus_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为三种病毒结构示意图，从左至右依次为烟草花叶病毒、腺病毒、大肠杆菌噬菌体。图中数字标注了病毒的结构，请按顺序填写：\n①____ ②____ ③____ ④____ ⑤____ ⑥____",
        "image": "image31.png",
        "answer": ["蛋白质外壳(或衣壳)", "遗传物质(RNA)", "蛋白质外壳(或衣壳)", "遗传物质(DNA)", "遗传物质(DNA)", "蛋白质外壳(或衣壳)"],
        "explanation": "病毒结构简单，无细胞结构，由蛋白质外壳和内部遗传物质组成。图中：①②为烟草花叶病毒（①蛋白质外壳、②RNA）；③④为腺病毒（③蛋白质外壳、④DNA）；⑤⑥为大肠杆菌噬菌体（⑤DNA、⑥蛋白质外壳）。病毒必须寄生在活细胞内才能繁殖。",
    },
    {
        "id": "shitu_class_01",
        "chapter_id": "bio_8_6_1",
        "image": "image34.png",
        "question": "生物分类的基本单位是?",
        "type": "select",
        "options": ["界", "门", "种", "科"],
        "answer": 2,
        "explanation": "种(物种)是生物分类的基本单位。",
    },
    {
        "id": "shitu_class_02",
        "chapter_id": "bio_8_6_1",
        "image": "image34.png",
        "question": "分类等级越低,生物之间的共同特征?",
        "type": "select",
        "options": ["越少", "越多", "不变", "无关"],
        "answer": 1,
        "explanation": "分类等级越低,生物之间的共同特征越多,亲缘关系越近。",
    },
    {
        "id": "shitu_leafbud_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为叶芽发育示意图，左图为叶芽纵切结构（数字1-3），右图为发育成的枝条（字母A-C）。请按顺序填写叶芽各部分及其发育结果：\n①____→A____ ②____→B____ ③____→C____",
        "image": "image36.png",
        "answer": ["生长点,顶芽", "幼叶,叶", "芽原基,侧芽"],
        "explanation": "叶芽发育：①生长点（位于芽顶端，细胞分裂使芽轴伸长）发育为A顶芽（或茎）；②幼叶（叶芽中的幼叶）发育为B叶；③芽原基（位于幼叶腋部）发育为C侧芽。叶芽是未发育的枝条。",
    },
    {
        "id": "shitu_pollination_01",
        "chapter_id": "bio_7_2_2",
        "image": "image37.png",
        "question": "图中①花粉萌发出什么结构?",
        "type": "select",
        "options": ["花粉管", "根毛", "菌丝", "芽体"],
        "answer": 0,
        "explanation": "花粉落到柱头上后萌发出花粉管。",
    },
    {
        "id": "shitu_pollination_02",
        "chapter_id": "bio_7_2_2",
        "image": "image37.png",
        "question": "图中精子与卵细胞结合形成什么?",
        "type": "select",
        "options": ["种子", "受精卵", "胚珠", "子房"],
        "answer": 1,
        "explanation": "精子与卵细胞结合形成受精卵,将来发育成胚。",
    },
    {
        "id": "shitu_microscope_05",
        "chapter_id": "bio_7_1_1",
        "image": "image4.png",
        "question": "转动图中⑧可以使镜筒升降幅度较小,该结构名称是?",
        "type": "image_fill",
        "answer": ["细准焦螺旋"],
        "explanation": "8是细准焦螺旋,使镜筒升降幅度较小,用于精细调焦。",
    },
    {
        "id": "shitu_leaf_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为叶片结构示意图，左图为叶片横切面（数字①-⑤），右图为气孔放大图（数字⑦-⑨）。请按顺序填写各数字代表的结构名称：\n①____ ②____ ③____ ④____ ⑤____\n⑦____ ⑧____ ⑨____",
        "image": "image40.jpeg",
        "answer": ["上表皮", "叶肉(栅栏组织和海绵组织)", "叶脉(维管束),内有导管和筛管", "下表皮", "气孔", "保卫细胞,呈半月形", "气孔,由两个保卫细胞围成", "孔下室,有利于气体扩散"],
        "explanation": "叶片结构：①上表皮（保护作用）、②叶肉（含栅栏组织和海绵组织，进行光合作用）、③叶脉（维管束，内有导管运输水和无机盐、筛管运输有机物）、④下表皮、⑤气孔（气体交换和水分蒸腾的门户）；右图气孔放大：⑦保卫细胞（呈半月形，控制气孔开闭）、⑧气孔（由两个保卫细胞围成）、⑨孔下室（有利于气体扩散）。",
    },
    {
        "id": "shitu_ovary_02",
        "chapter_id": "bio_7_2_2",
        "image": "image41.png",
        "question": "图中⑤所示的结构名称是?",
        "type": "select",
        "options": ["子房壁", "珠被", "胚珠", "受精卵"],
        "answer": 2,
        "explanation": "5是胚珠,将来发育成种子。",
    },
    {
        "id": "shitu_ovary_03",
        "chapter_id": "bio_7_2_2",
        "image": "image41.png",
        "question": "受精后,子房发育成?",
        "type": "select",
        "options": ["果实", "种子", "果皮", "胚"],
        "answer": 0,
        "explanation": "受精后,子房发育成果实,子房壁发育成果皮,胚珠发育成种子。",
    },
    {
        "id": "shitu_photo_04",
        "chapter_id": "bio_7_3_2",
        "image": "image42.png",
        "question": "检验绿叶在光下制造有机物的实验中,首先要把天竺葵放在暗处一昼夜,目的是?",
        "type": "select",
        "options": ["消耗叶片内原有的淀粉", "增加叶片内的淀粉", "使叶片变软", "促进光合作用"],
        "answer": 0,
        "explanation": "暗处理是为了耗尽叶片中原有的淀粉,排除干扰。",
    },
    {
        "id": "shitu_photo_05",
        "chapter_id": "bio_7_3_2",
        "image": "image42.png",
        "question": "检验绿叶在光下制造有机物的实验中,用什么试剂检验淀粉?",
        "type": "select",
        "options": ["碘液", "酒精", "清水", "盐水"],
        "answer": 0,
        "explanation": "碘液遇淀粉变蓝,是检验淀粉的常用试剂。",
    },
    {
        "id": "shitu_photo_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为绿色植物三大生理活动示意图。图中字母A-C分别表示三种不同的生理活动。请按顺序填写各字母代表的生理活动名称：\nA____ B____ C____",
        "image": "image43.png",
        "answer": ["呼吸作用", "蒸腾作用", "光合作用"],
        "explanation": "绿色植物三大生理活动：A呼吸作用（吸收氧气、释放二氧化碳，分解有机物释放能量）；B蒸腾作用（水分以水蒸气形式从叶片散失，促进水分和无机盐运输，降低叶片温度）；C光合作用（吸收二氧化碳、释放氧气，合成有机物储存能量，场所是叶绿体）。",
    },
    {
        "id": "shitu_photo_01",
        "chapter_id": "bio_7_3_2",
        "image": "image44.png",
        "question": "光合作用的原料是?",
        "type": "select",
        "options": ["氧气和有机物", "二氧化碳和水", "水和有机物", "氧气和二氧化碳"],
        "answer": 1,
        "explanation": "光合作用以二氧化碳和水为原料,在光下合成有机物并释放氧气。",
    },
    {
        "id": "shitu_photo_02",
        "chapter_id": "bio_7_3_2",
        "image": "image44.png",
        "question": "光合作用的产物是?",
        "type": "select",
        "options": ["氧气和有机物", "二氧化碳和水", "水和有机物", "氧气和二氧化碳"],
        "answer": 0,
        "explanation": "光合作用产生有机物(储存能量)和氧气。",
    },
    {
        "id": "shitu_photo_03",
        "chapter_id": "bio_7_3_2",
        "image": "image44.png",
        "question": "光合作用的场所是?",
        "type": "select",
        "options": ["线粒体", "叶绿体", "细胞核", "液泡"],
        "answer": 1,
        "explanation": "叶绿体是光合作用的场所,能将光能转化为化学能。",
    },
    {
        "id": "shitu_cell_hotspot",
        "chapter_id": "bio_7_1_2",
        "image": "image5.png",
        "question": "下图为动植物细胞结构图，图中红色标注了细胞的各部分结构。请在图中白色输入框内填写各结构名称：",
        "type": "image_hotspot",
        "hotspots": [
            {"label": "细胞壁", "x": 0.28, "y": 0.20, "width": 8},
            {"label": "叶绿体", "x": 0.28, "y": 0.42, "width": 8},
            {"label": "液泡", "x": 0.28, "y": 0.62, "width": 8},
            {"label": "细胞核", "x": 0.56, "y": 0.18, "width": 8},
            {"label": "细胞膜", "x": 0.56, "y": 0.35, "width": 8},
            {"label": "细胞质", "x": 0.56, "y": 0.52, "width": 8},
            {"label": "线粒体", "x": 0.56, "y": 0.72, "width": 8},
        ],
        "answer": ["细胞壁", "叶绿体", "液泡", "细胞核", "细胞膜", "细胞质", "线粒体"],
        "explanation": "植物细胞特有结构：细胞壁（支持和保护）、叶绿体（光合作用场所）、液泡（储存细胞液）。动植物细胞共有结构：细胞核（含遗传物质，控制生命活动）、细胞膜（控制物质进出）、细胞质（代谢场所）、线粒体（呼吸作用，提供能量）。",
    },
    {
        "id": "shitu_repro_03",
        "chapter_id": "bio_8_5_1",
        "image": "image51.png",
        "question": "受精的场所是?",
        "type": "select",
        "options": ["卵巢", "输卵管", "子宫", "阴道"],
        "answer": 1,
        "explanation": "精子与卵细胞在输卵管内结合形成受精卵。",
    },
    {
        "id": "shitu_digest_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为营养物质消化过程示意图，展示了淀粉、蛋白质、脂肪在消化道内的消化过程。图中数字①-⑥表示消化过程中的中间产物或最终产物。请按顺序填写：\n①____ ②____ ③____ ④____ ⑤____ ⑥____",
        "image": "image54.png",
        "answer": ["麦芽糖", "葡萄糖", "多肽", "氨基酸", "脂肪微粒", "甘油和脂肪酸"],
        "explanation": "营养物质消化过程：淀粉→①麦芽糖（口腔唾液淀粉酶初步消化）→②葡萄糖（小肠内肠液、胰液彻底消化）；蛋白质→③多肽（胃内胃液初步消化）→④氨基酸（小肠内彻底消化）；脂肪→⑤脂肪微粒（小肠内胆汁乳化）→⑥甘油和脂肪酸（小肠内肠液、胰液消化）。",
    },
    {
        "id": "shitu_mushroom_all",
        "type": "image_fill",
        "chapter": "shitu_all",
        "question": "下图为蘑菇结构示意图，图中数字1-5标注了蘑菇的各部分结构。请按顺序填写各数字代表的结构名称：\n①____ ②____ ③____ ④____ ⑤____",
        "image": "mushroom.png",
        "answer": ["孢子", "菌丝", "菌盖", "菌柄", "菌盖下方(菌褶)"],
        "explanation": "蘑菇结构：①孢子（繁殖细胞，产生于菌褶中）；②菌丝（地下部分，吸收水分和有机物）；③菌盖（地上部分顶部，保护菌褶）；④菌柄（支撑菌盖）；⑤菌盖下方/菌褶（产生孢子的繁殖结构）。蘑菇属于真菌，不能进行光合作用，依靠菌丝吸收现成的有机物。",
    },
    {
        "id": "shitu_mushroom_06",
        "chapter_id": "bio_8_5_4",
        "image": "mushroom.png",
        "question": "蘑菇的繁殖器官是什么？",
        "type": "select",
        "options": ["菌盖", "菌柄", "菌褶", "菌丝"],
        "answer": "C",
        "explanation": "菌褶是蘑菇的繁殖器官，菌褶内产生孢子用于繁殖。",
    },
    {
        "id": "shitu_mushroom_07",
        "chapter_id": "bio_8_5_4",
        "image": "mushroom.png",
        "question": "蘑菇的地下部分③主要功能是什么？",
        "type": "select",
        "options": ["光合作用", "吸收水分和有机物", "产生孢子", "支撑地上部分"],
        "answer": "B",
        "explanation": "地下菌丝体（③）的主要功能是吸收水分和有机物，蘑菇是真菌，不能进行光合作用。",
    },
]


def get_all_shitu_questions():
    return SHITU_QUESTIONS
