name: Build Android APK

on:
  push:    branches       main    
  workflow_dispatch:

jobs:
  build    runs-on ubuntu-latest     
    
                uses      
          with         '3'            
            
                            pip3 install --upgrade pip setuptools wheel cython==0                  
    
                           cd $GITHUB_WORKSPACE       
                
        
                          echo           ARTIFACT_NAME                         find               
            
                                                path                             
  
                           echo                             path               buildozer_log.txt